name: Assign

on:
  pull_request:
    types: [opened, unassigned]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh pr edit $NUMBER --add-assignee "@me"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
